name: Deploy training pipeline
on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version"
        type: string
        required: true
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
env:
  PYTHON_PROJECT_VERSION: "${{ inputs.python_version}}"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ENV_NAME: ${{ secrets.ENV_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: PR checkout
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_PROJECT_VERSION }}
      - name: Install requirements
        run: |
          cd requirements
          python -m pip install --upgrade pip
          pip install -r dev.txt
      - name: deploy experiment
        run: |
          cd src
          python cli.py
