name: CI
on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version"
        type: string
        required: true

env:
  PYTHON_PROJECT_VERSION: "${{ inputs.python-version }}"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: PR checkout
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_PROJECT_VERSION }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          cd requirements
          pip install -r dev.txt
      - name: Nox
        run: nox
