name: Deploy train pipeline
on:
  pull_request:
    branches: [ main ]

jobs:
  CI:
    use: sm-architecture/.github/workflows/ci@dev
    with:
      python-version: '3.8'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ENV_NAME: ${{ secrets.ENV_NAME }}
  QA:
    needs: CI
    use: sm-architecture/.github/workflows/cd@dev
    environment: QA
    with:
      python-version: '3.8'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ENV_NAME: ${{ secrets.ENV_NAME }}
  PROD:
    needs: [CI, QA]
    use: sm-architecture/.github/workflows/cd@dev
    environment: PROD
    with:
      python-version: '3.8'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ENV_NAME: ${{ secrets.ENV_NAME }}
