name: Deploy train pipeline
on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    use: sm-architecture/.github/workflows/ci@main
    with:
      python-version: '3.8'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}