name: Deploy train pipeline
on:
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: PR checkout
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install requirements
        run: |
          cd requirements
          python -m pip install --upgrade pip
          pip install -r dev.txt
          conda env list
      - name: Fire SageMaker
        id: sm_train
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'   # optional: defaults to us-east-1
          AWS_DEFAULT_REGION: 'eu-west-1'
          PR_NUMBER: ${{ github.event.number }} # Only available for pr (no push)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src
          python cli.py
